version: '3'

services:
  # web:
  #   container_name: school
  #   build:
  #     context: .
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  db:
    container_name: hellodb
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: mo@mo.com
      PGADMIN_DEFAULT_PASSWORD: mo-pass